### ISSUE TITLE
Main Menu Problem

### ISSUE THREAD

**Issue by RunawaySheld123** [raysfire/rayshud#139]
I Have Problem With The Main Menu With The Rayshud Installer
https://steamcommunity.com/sharedfiles/filedetails/?id=1901384752

**Comment by CriticalFlaw** [comment]
Are you using the latest installer version? This looks like a version mismatch issue. Try doing a clean reinstall of rayshud with the latest installer version (3.3).

**Comment by RunawaySheld123** [comment]
Oh Right

**Comment by CriticalFlaw** [comment]
Correction, this issue was being caused by the installer when switching between main menu styles. The updated version of the installer (3.3.1) has been released.

**Bug Report**: https://github.com/CriticalFlaw/rayshud-Installer/issues/29
**Download**: https://github.com/CriticalFlaw/rayshud-Installer/releases
