### ISSUE TITLE
Visual HUD Glitches

### ISSUE THREAD

**Issue by Ashetf2** [raysfire/rayshud#145]
### 1. Some numbers looks cut off on the scoreboard and round timer.
![2](https://user-images.githubusercontent.com/63692647/79488432-55ac2100-7fdf-11ea-9987-aea1fb2c76f3.jpg)
![1](https://user-images.githubusercontent.com/63692647/79488426-547af400-7fdf-11ea-8860-652a53f60db6.jpg)

### 2. On the main menu, the alert button will overlap the selecting gamemode menu. Also, the number of client of tf2 overlaps the disconnect button.
![3](https://user-images.githubusercontent.com/63692647/79488433-5644b780-7fdf-11ea-878e-15d0eec9ca90.jpg)
![5](https://user-images.githubusercontent.com/63692647/79488436-5644b780-7fdf-11ea-8874-733c330d9280.jpg)

### 3. In payload, the arrow sign when the payload is moving back isnt in the center.
![6](https://user-images.githubusercontent.com/63692647/79488438-56dd4e00-7fdf-11ea-8329-0c057a26fe46.jpg)

### 4. In control point, you can see the red border when blu is capturing it. 
![7](https://user-images.githubusercontent.com/63692647/79488440-5775e480-7fdf-11ea-9985-1643ef101354.jpg)

### 5. Some weapon images overlap the player name of the player in the death cam. Also I suggest making the background more transparent.
![8](https://user-images.githubusercontent.com/63692647/79488441-5775e480-7fdf-11ea-8534-f0f3dfaac94e.jpg)

### 6 When playing as the Spy, the render of the player you are disguised is cut off if the enemy carries a large weapon (i.e. flamethrower). Also the chat overlaps the rectangle of information (h.p./name/wep of disguised) a bit.
![9](https://user-images.githubusercontent.com/63692647/79488445-580e7b00-7fdf-11ea-9d82-b5c04875b275.jpg)

**Comment by CriticalFlaw** [comment]
Had to update your original post a little bit to organize all the issues.

Point 1; has to do with your current resolution and how the game scales fonts. So if you're on a lower resolution lot of the fonts will look cut off like that even though they are given a lot of space, see screenshot below. I don't think this is something that can be fixed on my end.

![image](https://user-images.githubusercontent.com/6818236/79910360-94314980-83ec-11ea-9ba4-2ea686a1e2f3.png)

Point 2; the alert you see is for when that game-mode is inaccessible, it is not the notification alert so that's normal. What you see with the Disconnect button isn't actually an overlap, the button has a lowered alpha channel meaning it's semi-transparent so you see what's behind it. I supposed the alpha can be increased but it isn't a bug per se.

Points 3-6; should be fairly easy to correct. Though the chat overlap will be a change in the installer since that's what sets the lowered chat position to what it is. The rest will be correct in a later update.

**Comment by Ashetf2** [comment]
About the first point, what is the "normal" resolution? I was trying with some resolutions and the glitch stills. My default resolution is 1366x768, also default to my pc and my screen.

**Comment by CriticalFlaw** [comment]
The resolution I work in is 1920x1080

**Comment by drunderscore** [comment]
@Ashetf2 Your resolution is *almost* 16:9, which is the most common widescreen aspect ratio (of which, 1920x1080 is).

This is most likely the reason things look slightly off, as your resolution is abnormal.

**Comment by CriticalFlaw** [comment]
Visual bugs at points 3-6 have been corrected in 26c29f808aa068cc57166c65dd12d63be3a25bde

Thank you for reporting them.
