### ISSUE TITLE
Streamer mode doesn't hide info in deathcam or casual pregame screen

### ISSUE THREAD

**Issue by Fibly** [raysfire/rayshud#194]
When using streamer mode, the deathcam still displays the killername and weapon. The server players are all visible when starting the match. 

![image](https://user-images.githubusercontent.com/82604817/236649350-f18facc4-3eb0-46fc-b4c9-21d7a7a6fe5c.png)
![image](https://user-images.githubusercontent.com/82604817/236649362-a3816646-9637-4662-9372-1dc5c44178b0.png)

**Comment by CriticalFlaw** [comment]
How did you enable streamer mode on your side?

**Comment by Fibly** [comment]
\custom\rayshud\#customizations

Changed the folder name from "_streamermode" to "streamermode"

**Comment by CriticalFlaw** [comment]
Fixed in 45d4235b4eebb3925b72db4efb35d46fe1dbe720. I'd suggest installing a fresh copy of the HUD.
Also instead of renaming the `_streamermode` folder, move it into the `_enabled` folder same as other customizations.

![20230507230826_1](https://user-images.githubusercontent.com/6818236/236983790-6b569dfe-5bd1-4ac2-9142-4290ef0f87da.jpg)
![20230508230030_1](https://user-images.githubusercontent.com/6818236/236983791-178bc5fb-707f-4aaa-9f11-856ea5846d53.jpg)
