### ISSUE TITLE
Some minor issues after JU

### ISSUE THREAD

**Issue by IdleGandalf** [raysfire/rayshud#67]
I know you said there will be minor problems left, I'm just listing them here for better a overview.

**JU related**
- [x] ~~Weird number appearing left of health~~
- [x] ~~Badge/level bar is misplaced in main menu (16:9)~~
- [ ] Badge/level bar is misplaced in main menu (16:10)
- [x] ~~Diffuse darkish background when opening 'Find Game' doesn't go all the way down~~
- [x] ~~'Party/Nav Top bar' will clip content when in Loadout/Stats~~
- [x] Score numbers on winning 'screen' are somewhat clipped

**Other**

- ~~CTF messages are little too low, they get into health/ammo numbers~~ (#69)
- ~~Map and gamemode text in loading screen is too high (topbar overlaps)~~ (#70)

Will edit more things in when they come up.

_Edit 1: added more issues_
_Edit 2: added more issues_
_Edit 3: separated some issues_

Attaching some images to make things clearer

![20171021164922_1](https://user-images.githubusercontent.com/4494131/31852911-58eb09ce-b680-11e7-8573-4006b31690c7.jpg)
![20171021173039_1](https://user-images.githubusercontent.com/4494131/31853350-3ef686a4-b687-11e7-9fbe-1c6b77c8c9a6.jpg)

**Comment by CriticalFlaw** [comment]
Thanks for reporting them. I've noticed these are well. The badge was annoying to position as is in 16:9 because it would only go so far to the left. The dark overlay is in the default game files, so I'll need to modify them myself later and lower the tabs in the inventory screen.

**Comment by IdleGandalf** [comment]
Yea I can imagine that. Added some more after playing one round ctf, didn't test cp yet.

**Comment by CriticalFlaw** [comment]
Released the fix for the max health number not displaying (screenshot #3)

**Comment by CriticalFlaw** [comment]
I would remove or categorize the last two issues (CTF messages are little too low, they get into health/ammo numbers) and (Map and gamemode text in loading screen is too high (topbar overlaps)) as optional or miscellaneous, because those have been around for a while and are not Jungle Inferno specific which is the focus right now

**Comment by IdleGandalf** [comment]
Sure, its no big deal.

**Comment by BeebBeebBoob** [comment]
![20171021190416_1](https://user-images.githubusercontent.com/32985153/31853600-dd754af2-b693-11e7-83bf-83607b4b4b6b.jpg)
Can you fix this? And fix button that opens "accept or cancel notification"

**Comment by CriticalFlaw** [comment]
That may be an engine bug, don't think I can fix it, I'll try though

**Comment by BeebBeebBoob** [comment]
![20171021192052_1](https://user-images.githubusercontent.com/32985153/31853681-54057cfe-b695-11e7-9ef3-09cd16dccd4f.jpg)
![20171021192101_1](https://user-images.githubusercontent.com/32985153/31853685-67979e1e-b695-11e7-8d07-0b2b419e5a62.jpg)
Just another a pictures of that bug

**Comment by explosivedeer** [comment]
This probably isn't of huge concern, but the "hitbox" on the medal for the main menu is shifted to the left a bit too far. (i need to click that shit)

**Comment by CriticalFlaw** [comment]
I'll have a fix for the war paint issue in a few hours.

**Comment by CriticalFlaw** [comment]
The new item notification page, top bar overlap in loadout/stats and store, and badge hitbox misaligned (for 16:9 only) has been fixed as of the latest version (v2017.1022). The dimmed background when opening the Find Game button is hardcoded and has to be fixed as Valve. Also the Phlogistinator and Gas Passer item effect meters overlap and that's also a Valve bug.

**Comment by IdleGandalf** [comment]
Gonna test this later, thanks for the quick patches.

**Comment by IdleGandalf** [comment]
I tested this and it looks good, the only thing left is that the badge is still misaligned for me on 16:10, but thats no big deal.

**Comment by goldnharl** [comment]
on 4:3, the badge/level bar/box on the main menu is placed far to the left, where half of it is offscreen entirely.

**Comment by CriticalFlaw** [comment]
The score numbers should be fixed now as well as the badge in 16:10 (I've redesigned the main menu). Download the latest version, check it out and if it's all good, close this ticket please.

**Comment by groovius** [comment]
This just started after rayshud installation.  Happens when spectating, scoping, and when switching class.
![screenshot 23](https://user-images.githubusercontent.com/33206500/32148610-f520584e-bcb6-11e7-81d2-a51aaa4bff61.png)
![screenshot 24](https://user-images.githubusercontent.com/33206500/32148618-04f70b96-bcb7-11e7-9076-9e695b40b7c4.png)


![screenshot 26](https://user-images.githubusercontent.com/33206500/32148602-da3756cc-bcb6-11e7-985d-d46385d0829f.png)

**Comment by CriticalFlaw** [comment]
Do you have transparent viewmodels enabled? If so, there might be something wrong with your config, because these are not issues based by the HUD overlay

**Comment by CriticalFlaw** [comment]
@IdleGandalf can you check if the badge is placed correctly in 16:10 with the redesigned main menu? If so, please close this issue, the screenshots by @groovius are not rayshud related (likely transparents viewmodels, which I do not troubleshoot) and the fix for the win panel scores has been added to the upcoming update branch https://github.com/raysfire/rayshud/pull/81

**Comment by IdleGandalf** [comment]
Yea all good now, thanks for the redesign, looks good!

**Comment by IdleGandalf** [comment]
Yea all good now, thanks for the redesign, looks good!
